// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfdaKeiQP0V6ROhjCke6RQB8a3iyMv81w',
    appId: '1:34479116262:web:c2b8948e84a5cc42489027',
    messagingSenderId: '34479116262',
    projectId: 'findyourjob-9410e',
    authDomain: 'findyourjob-9410e.firebaseapp.com',
    storageBucket: 'findyourjob-9410e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrar9chizNYbwYMIAzj97PKc1eelxqJmo',
    appId: '1:34479116262:android:7e4d439c72c12bf7489027',
    messagingSenderId: '34479116262',
    projectId: 'findyourjob-9410e',
    storageBucket: 'findyourjob-9410e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEXfpaUqILWGBRUiuOszFxE3dK1n5QP9w',
    appId: '1:34479116262:ios:188efaa7f1139cbb489027',
    messagingSenderId: '34479116262',
    projectId: 'findyourjob-9410e',
    storageBucket: 'findyourjob-9410e.appspot.com',
    iosBundleId: 'com.example.findYourJob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEXfpaUqILWGBRUiuOszFxE3dK1n5QP9w',
    appId: '1:34479116262:ios:b89565bc7e7f2493489027',
    messagingSenderId: '34479116262',
    projectId: 'findyourjob-9410e',
    storageBucket: 'findyourjob-9410e.appspot.com',
    iosBundleId: 'com.example.findYourJob.RunnerTests',
  );
}
